config/routes.rb
Mytest::Application.routes.draw do
  resources :dogs

  root "foo#index"
  get "foo/helloworld" => "foo#print_hello"
  resources :personnes

  

end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/models/personne.rb
class Personne < ActiveRecord::Base
	validates :name, :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dog }
      else
        format.html { render action: 'new' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name)
    end
end

app/controllers/foo_controller.rb
class FooController < ApplicationController
  def index
   
  end
  
  def print_hello
    @toto = Personne.first
    render "hello"

  end 
end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
	before_filter :toto

	def toto 
		@titi = 'tata'
	end

	def new
		 @personne = Personne.new
	end

	def create
		@personne = Personne.new(person_params)
		if @personne.save
			redirect_to @personne
    else
      render :new
    end
	end

	def show
		@personne = Personne.find(params[:id])
	end

	def index
		@personnes = Personne.all
	end

	def destroy
		#@personne = Personne.delete
		@personne = Personne.find(params[:id])
    	@personne.delete
	end

	private
    
    def person_params
      params.require(:personne).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/foo_helper.rb
module FooHelper
end

app/helpers/personnes_helper.rb
module PersonnesHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/foo/hello.html.erb
Hello <%=@toto%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mytest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/personnes/destroy.slim
The person with name "<%= @personne.name %>" and id "<%= @personne.id %>" has been destroyed !!!!!!

app/views/personnes/index.slim
= @titi 
- @personnes.each do |p| 
	= p.name 
	= link_to 'Supprimer' , personne_path(p), method: :delete 
	br
br
= link_to 'Creer une personne', new_personne_path 

app/views/personnes/new.slim
- if @personne.errors.any? 
	= @personne.errors.inspect

= form_for @personne do |f| 
	| Name : 
	= f.text_field  :name 
	br
	| Age : 
	= f.text_field  :age 
	= f.submit 

app/views/personnes/show.slim
Id :  <%= @personne.id %>
<br/>
Name : <%= @personne.name %>